### ISSUE TITLE
Problem with variable testing

### ISSUE THREAD

**Issue by gragia79** [tattersoftware/codeigniter4-visits#10]
if I use ci4 with the variable CI_ENVIRONMENT = testing it gives me the following error:

```
Tatter\Visits\Exceptions\VisitsException
Table "visits" missing for visit storage.
VENDORPATH/tatter/visits/src/Visits.php at line 84
```
same problem if I execute the command with the variable CI_ENVIRONMENT = testing:

`sudo php spark migrate -all`

```
CodeIgniter v4.1.5 Command Line Tool - Server Time: 2022-01-10 04:19:24 UTC+01:00

ERROR: 404
Il Controller o il suo metodo non è stato trovato: \App\Controllers\Cimigrate::index

```
if I use CI_ENVIRONMENT = development it does not give problems .

**Comment by MGatner** [comment]
You should never set you environment to "testing" manually - that is reserved for running unit tests and will indicate to many classes to run in test mode. In this case, the Database layer thinks you are running unit tests so the default database group changes, meaning none of your migrations are detected. 

This is it an issue with `Visits` so closing. If you need more help please go to the CI4 forums.

**Comment by gragia79** [comment]
Thanks you
