### ISSUE TITLE
$resetAfter seems not working

### ISSUE THREAD

**Issue by jozefrebjak** [tattersoftware/codeigniter4-visits#21]
It seems like a `$resetMinutes` is not working, I tried a new version of library and it's add new entry in database after visit instead of increment `views` column. 

![CleanShot 2022-07-11 at 13 35 32@2x](https://user-images.githubusercontent.com/36922215/178255726-d295e8e0-3585-42d0-a381-cfce408dd643.png)

**Comment by MGatner** [comment]
Did you update your Config file? The property has been renamed and is now in seconds instead of minutes: https://github.com/tattersoftware/codeigniter4-visits/blob/develop/src/Config/Visits.php#L17-L22

**Comment by jozefrebjak** [comment]
I'm just installed with composer and using src config, not extended one.  So my bad, `public int $resetAfter = HOUR;` this is not working.

**Comment by MGatner** [comment]
Okay thanks I will take a look.

**Comment by MGatner** [comment]
I assume this means your are using the default `ip_address` tracking method right?

**Comment by jozefrebjak** [comment]
@MGatner Maybe I have an issues with `datetime` in database. 

```php
$since = Time::now()->subSeconds(...)->format(...) string (19) "2022-07-11 10:49:34"
```

returing for me in controller `dd($since = Time::now()->subSeconds(...)->format(...) string (19) "2022-07-11 10:49:34")`

`
string (19) "2022-07-11 10:49:34"
`

but in database in UTC is one hour more

**Comment by jozefrebjak** [comment]
@MGatner Yes, just default Visits Config in `src/Config`

**Comment by jozefrebjak** [comment]
@MGatner Here is the issue

```sql
SELECT * FROM `visits` WHERE `host` = 'localhost' AND `path` = '/clients' AND `query` = '' AND `ip_address` = '192.168.112.1' AND `created_at` >= '2022-07-11 11:03:51' LIMIT 1
```

`ip_address` is not string but integer

**Comment by jozefrebjak** [comment]
For me it works only with `user id`, `session id` it's not working too, it's trying to find somehow with different session_id as it's stored in db.

**Comment by MGatner** [comment]
@jozefrebjak Please try the linked PR for using IP address tracking; simple blunder on my part using the cast version for database lookup.

I am looking into the session ID tracking; it isn't apparent to me why that would not work but generating a session ID during tests is actually kind of complicated.

**Comment by MGatner** [comment]
Actually I just needed to run the test in a separate process. Session ID tracking appears to be working fine - if you can gather any more information I am happy to look into it more. Definitely check on your framework session settings and make sure that is working as expected.

**Comment by jozefrebjak** [comment]
@MGatner tested [#PR22](https://github.com/tattersoftware/codeigniter4-visits/pull/22) and now it's working for `ip_address` fine. `session_id` is not, it doesn't increment `views` column. In database is stored different `session_id` then in Database query from debugbar.

**Comment by MGatner** [comment]
> In database is stored different `session_id` then in Database query from debugbar

How is it different? Truncated? It looks like this migration specifics `32` length but in some instances it can be longer.

**Comment by jozefrebjak** [comment]
I'm running dev environment in docker on my mac. Here is the `session_id` stored in database.

```sh
217d8560580ab170a52bf6b26b24f440
```

And this is an query in debugbar:

```sql
SELECT * FROM `visits` WHERE `host` = 'localhost' AND `path` = '/contacts' AND `query` = '' AND `session_id` = '217d8560580ab170a52bf6b26b24f4403d24cb34' AND `created_at` >= '2022-07-11 19:31:54' LIMIT 1
``` 

So yes, it's truncated.

**Comment by MGatner** [comment]
Thanks for that! I will resolve this issue with the current PR and start a new issue to track this.

**Comment by jozefrebjak** [comment]
@MGatner By the way, thank you for perfect package.

**Comment by MGatner** [comment]
You're welcome! Far from perfect, as we see ;) I appreciate the help testing and making it better!
