### ISSUE TITLE
Session ID Truncated

### ISSUE THREAD

**Issue by MGatner** [tattersoftware/codeigniter4-visits#23]
Session IDs are getting truncated to 32 digits, causing `findSimilar()` to fail to identify repeat visits.

See: https://github.com/tattersoftware/codeigniter4-visits/issues/21#issuecomment-1180842482

**Comment by MGatner** [comment]
@jozefrebjak please test the `session-length` branch.

**Comment by jozefrebjak** [comment]
@MGatner Now it works as expected.

**Comment by MGatner** [comment]
Thanks for testing!
