### ISSUE TITLE
getIpAddress() always return null in view

### ISSUE THREAD

**Issue by jozefrebjak** [tattersoftware/codeigniter4-visits#25]
`getIpAddress()` is returning IP Address as expected in backend, but in view it's always null. 

There is `is_int` check, but all variables in entity seems to return as string in view, I tried to cast `ip_address` as int, but it's not work to check if attribute is integer and also we want a string in view.

**Comment by MGatner** [comment]
This doesn't sound like an issue with this library; you may be better off going to the CodeIgniter forums or Slack.

If you want to share some of your actual code I can look at it but your description doesn't offer enough for diagnosis.

**Comment by jozefrebjak** [comment]
@MGatner I would like to build a frontend for visits table and when I want to show `ip_address` in table, then it's still `null`, because of function `getIpAddress()` in `Visit` entity:

```php
    /**
     * Converts integer IP addresses to their human pointed format.
     */
    public function getIpAddress(): ?string
    {
        if (is_int($this->attributes['ip_address'])) {
            return long2ip($this->attributes['ip_address']);
        }

        return null;
    }
```

This function is using `is_int()` function to determine if `$this->attributes['ip_address']` is integer, what is fine with backend, there it works as expected, but when I want to call what is `ip_address` in view like:

```php
<?php foreach ($visits as $visit) : ?>
    <th><?= $visit->ip_address ?></th>
<?php endforeach ?>
```

It returns always `null` instead of the IP Address like `10.0.0.1`.  

Is this behaviour expected ?

**Comment by MGatner** [comment]
It is not expected. It might be that the data in `$attributes` is actually a string coming out of the database. Could you change `is_int` to `is_numeric` and try it?

**Comment by jozefrebjak** [comment]
@MGatner `is_numeric` is the way how to check `int` values from database.  It works.

**Comment by MGatner** [comment]
Excellent! Thanks for catching this. I am on mobile but I will implement a fix later on desktop, or you can send over a PR (please include a test if so).

**Comment by jozefrebjak** [comment]
I'm used this entity function in one of my project where I'm using SSH and storing IP Address as an integer. I'm curious why it works when I call `$this->attributes['ip_address']` in entity with another function and it's translated correctly to the string format of the IP, but when I want to render it in view it's null.
