### ISSUE TITLE
ip_address

### ISSUE THREAD

**Issue by emersonamaro** [tattersoftware/codeigniter4-visits#30]
![image](https://user-images.githubusercontent.com/58705762/232586623-0cb5480e-ae2d-4844-91bd-224b547c2fd3.png)

I followed the explanations but the remote ip was not recognized.
I'm using php 7.4.3
and codeigniter 4.1.3
forgot something?

**Comment by MGatner** [comment]
It looks like you are using some sort of local proxy, and CodeIgniter isn't detecting the correct referral address. You may need to look at the CodeIgniter docs or proxy configuration.
